services:
  web:
    build:
      context: .
      command: python manage.py rynserver 0.0.0.0:8000
      volumes:
        - ./app:app
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data

